---
- name: installed different OS in different machines
  hosts: all
  become: yes
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start https
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2  package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy file
    copy:
      src: /home/Raj/index.html
      dest: /var/www/html
      mode: 0666
