---
- name: installed and start httpd service
  hosts: all
  become: yes
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: installed

  - name: start service
    service:
      name: httpd
      state: started
