---
- name: installed and start httpd service
  hosts: all
  become: yes
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: installed
    notify: start service   #dependancy handler name 

  handlers:  
  - name: start service                 #this run after run dependancy package
    service:
      name: httpd
      state: started
